### ISSUE TITLE
Suggesting a few small improvements

### ISSUE THREAD

**Issue by TBlueF** [AlexMitDemBart/Custom-Linked-List#1]
Just a few really small things i found that i think could be improved: :)

**1.**
[L33-L34](https://github.com/AlexMitDemBart/Custom-Linked-List/blob/master/src/MyLinkedList.java#L33-L34) and [L47-L48](https://github.com/AlexMitDemBart/Custom-Linked-List/blob/master/src/MyLinkedList.java#L47-L48) and [L59-L60](https://github.com/AlexMitDemBart/Custom-Linked-List/blob/master/src/MyLinkedList.java#L59-L60)
```java
head = new Node<T>(element);
tail = new Node<T>(element);
```
Head and tail should probably just point at the same `Node`-instance instead of two equal ones

**2.**
`addLast(T)` is basically the same function as `add(T)`, the only difference is that `add(T)` is using the `getLastNode()` function to make sure the the `tail` is actually the `tail` *(which should never be necessary)*.
So my suggestion would be to remove `getLastNode(T)` and make `add(T)` *(if you want to keep that method)* just proxy the `addLast(T)` function:
```java
public void add(T element){
    return addLast(element);
}
```

**3.**
I think on [L88](https://github.com/AlexMitDemBart/Custom-Linked-List/blob/master/src/MyLinkedList.java#L88) and [L107](https://github.com/AlexMitDemBart/Custom-Linked-List/blob/master/src/MyLinkedList.java#L107) if any of the elements in the list contains the value `null`, you'd get a `NullPointerException` in that line *(calling `.equals()` on ` null`)*

**4.**
I might have missed something obvious, but i think you don't need the `cursorIsOnHead` ([L124](https://github.com/AlexMitDemBart/Custom-Linked-List/blob/master/src/MyLinkedList.java#L124)) check at all? The `next()` function seems to do the same for both states :D

**Comment by AlexMitDemBart** [comment]
Thanks for the suggested improvements. I have implemented your ideas in the previous commit. 
I am very glad with your efforts.

I changed L33-L34 and L47-L48 and L59-L60 from

```java
head = new Node<T>(element);
tail = new Node<T>(element);
```

to

```java
Node<T> newNode = new Node<T>(element);
            head = newNode;
            tail = newNode;
```

I implemented your suggestion for the add methods, i like the idea of the proxy method call. I also took a look on the possible    `NullPointerExceptions`  that you talked about. The exceptions will no longer occur.

I removed `cursorIsOnHead` and suprisingly the function behaviour is the same. 
unfortunately I can no longer explain what I was thinking when i was creating this boolean.
